version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: hinomontaj-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hinomontaj
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - hinomontaj-network

volumes:
  postgres_data:

networks:
  hinomontaj-network:
    driver: bridge 